name: ci
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Setup BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.2.1
      - name: Checkout
        uses: actions/checkout@v3
      - name: make
        run: make all
